// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    F2e_logo: typeof import('./src/components/icons/f2e_logo.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    IcCross: typeof import('./src/components/icons/IcCross.vue')['default']
    IcStar: typeof import('./src/components/icons/IcStar.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
