// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    F2e_logo: typeof import('./src/components/icons/f2e_logo.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    IcCross: typeof import('./src/components/icons/IcCross.vue')['default']
    IcDialog: typeof import('./src/components/icons/IcDialog.vue')['default']
    IcLightning: typeof import('./src/components/icons/IcLightning.vue')['default']
    IcPosterBadge1: typeof import('./src/components/icons/IcPosterBadge1.vue')['default']
    IcPosterBadge2: typeof import('./src/components/icons/IcPosterBadge2.vue')['default']
    IcStar: typeof import('./src/components/icons/IcStar.vue')['default']
    IcTapeMobile: typeof import('./src/components/icons/IcTapeMobile.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Poster: typeof import('./src/components/Poster.vue')['default']
    Questions: typeof import('./src/components/Questions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Themes: typeof import('./src/components/Themes.vue')['default']
  }
}
